### ISSUE TITLE
Fix I2C

### ISSUE THREAD

**Issue by Jordan-Limonov** [frc3197/2019-FRC#1]
RoboRIO and REV Color Sensor V2 are not communicating.

Device Documentation (Addresses on Pg. 17) - http://www.revrobotics.com/content/docs/TMD3782_v2.pdf

Chief Delphi issue thread - https://www.chiefdelphi.com/t/rev-color-sensor-v2-and-roborio-communication/342075

See branch colorsensor for code current to this issue.

**Comment by Jordan-Limonov** [comment]
Following is a checklist for 1/19/2019

- [x] Connect to RoboRIO
- [ ] Communicate through I2C
- [x] Create Chief Delphi post for help
- [ ] Learn how to read colors
- [ ] Determine how colors should move robot

**Comment by Jordan-Limonov** [comment]
Initial Investigation Email:
>  So the Color Sensor V2 from REV Robotics uses an I2C port.
> 
> Lovely.
> 
> I found a forum where someone's asking around for any examples of using a device in the I2C port. They do seem to be trying to get an Arduino to communicate so we can just replace Arduino with the color sensor and we should be fine. I guess.
> https://www.chiefdelphi.com/t/anyone-ever-read-from-i2c-on-roborio/156020
> 
> The guy who answered gives a link to a repository that contains example code. It's 8:51 and I'm too tired to really look into it too much right now, but I'll try looking into it on Friday. If anyone finds anything else send it over in this email.
> 
> This other guy wrote an entire blog post about connecting and Arduino to the roboRIO. Could be worth looking into.
> http://errorlandia.blogspot.com/2017/12/arduino-to-roborio-i2c-communication.html
> 
> Anyone who wants to knows how I2C works (myself included) can look at this link. It does require VPN on the dreaded school network so that's a thing.
> https://i2c.info/
> 
> Coming back around to the color sensor, the following is the website and the PDF with the device specs and stuff.
> http://www.revrobotics.com/content/docs/REV-31-1537-DS.pdf
> 
> This is also the specific page containing the documentation for the I2C class in WPILib. If all else fails, some simple testing and printing should let us figure out what each method does. We should probably start with addressOnly() to confirm that we can access it before trying to read it with all that registerAddress nonsense.
> http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/I2C.html
> 
> Okay that's it. I'm out.

**Comment by Jordan-Limonov** [comment]
At this point, I'm going to just go through each of the register addresses and figure out what needs to be done.

We haven't written a byte to 0x00 yet. I think we might need to do that.

`
ColorSensor.write(0x00, 1); \\This enables the four-channel ADC.
ColorSensor.read(0x12, 8, ByteBuffer.allocate(8)); \\Hopefully this should return 0x60 or 0x69
`
If this returns true, then we can proceed to read from 0x16/0x17 (Red), 0x18, 0x19 (Green), and 0x1A/0x1B (Blue).
0x13 is for device status. We could read from that.

There's also a bunch of addresses for timing. We may want to look at those eventually (0x01, 0x03, 0x0D)

So basically, let's try out activating then reading the device ID. If that works we can proceed. I've given up on the Chief Delphi forum already lol.

Edit: In addition, each one of the commands as specified by WPILib return a true or false. True is for if the operation was aborted. False is for if the operation was successful. I believe we may have to return the ByteBuffer in order to read what we actually got from the I2C device. According to the following link, we just have to use `return buffer.get(0)` to get the info. For us that would mean using `System.out.println(buffer.get(0))`
https://www.chiefdelphi.com/t/writing-code-for-a-color-sensor/167303
Not sure how reliable this is though.

**Comment by spencrr** [comment]
https://www.chiefdelphi.com/t/i2c-over-usb-works-but-not-over-wifi-or-network-cable/342161

**Comment by hexhounds** [comment]
Not dealing with this anymore.

I'm tired of dealing with addresses. Maybe we'll figure it out next season or something.

**Comment by Jordan-Limonov** [comment]
Solved. SDA and SCL ports were swapped on RoboRIO so wires on color sensor were swapped.

Fix and general instructions now exist on documentation.
