### ISSUE TITLE
Stop things from breaking between autonomous and teleop

### ISSUE THREAD

**Issue by hexhounds** [frc3197/2019-FRC#17]
Switch the wrist and elbow gyro reset to not reset when teleop is enable, this breaks stuff between auto and teleop. Maybe add a boolean and set it true in autonomous, so it dosent run again? Or find a better way.

Same for the gyro, make sure it dosent break when enabled and disabled not at home.

**Comment by hexhounds** [comment]
!!!WARNING!!!:
Just putting the gyro reset in robot init instead of teleop init DOES NOT WORK. DO NOT DO THIS. THIS WILL BREAK THINGS.

**Comment by spencrr** [comment]
gyro reset not a problem (it resets continuously anyway while you are driving the wrist)

**Comment by spencrr** [comment]
Fixed by adding boolean in Robot that tries to reset in each `init`
