### ISSUE TITLE
Level 1 preset from home position

### ISSUE THREAD

**Issue by hexhounds** [frc3197/2019-FRC#19]
When moving to level 1 hatch or cargo, move the elevator up, move the arm, then move elevator down. Otherwise, this will break things by moving the arm and elevator down directly from home, and will just destroy the world.

**Comment by spencrr** [comment]
Let's be able to pass in a Flex object (that aligns both the arm and elevator) into Flex so that we can chain them together.

**Comment by spencrr** [comment]
Actually this is a quick fix because we can make Flex take in Command (which is what Flex is inherently).

**Comment by hexhounds** [comment]
don't worry about it
