### ISSUE TITLE
Camera Discussion Thread

### ISSUE THREAD

**Issue by spencrr** [frc3197/2019-FRC#35]
[Forum Thread](https://www.chiefdelphi.com/t/good-cameras-for-streaming/347989)

We need to fix our balance b/w FPS and resolution

**Comment by hexhounds** [comment]
Current camera is the [lifecam hd-3000](https://www.google.com/search?q=lifecam+hd-3000&rlz=1C1CHBF_enUS819US819&oq=Lifecam+HD-3000&aqs=chrome.0.0l6.383j0j7&sourceid=chrome&ie=UTF-8).
Possible alternative:
- [Logitech c930e](https://www.logitech.com/en-us/product/c930e-webcam)

**Comment by hexhounds** [comment]
axis cam is best and working now to work on vision
