### ISSUE TITLE
Handling for cases where Vision is detecting more than 2 contours

### ISSUE THREAD

**Issue by hexhounds** [frc3197/2019-FRC#46]
Currently the camera is positioned in such a way that if the green LED ring were placed right on the camera, it reflects light off the cord as well, giving us more than 4 contours. The code, as a result, is not working as predicted.

**Possible Solution: Eliminating the contours that have minimal change in size.**
This would require code that is continuously running throughout teleop that checks changes in the values of contourXs and contourAreas. We have to be able to get the difference between the previous value and the new value.
Correct me if my math is wrong, but this could involve derivatives. If the derivative of contourAreas[0] and/or contourXs[0] is near-zero, then that means the value is not changing. Thus, we can infer that it's the two unchanging contours and that we can safely ignore them.
Otherwise, we could do previousContourXs[0]-contourXs[0] and if the value is within +/- contourDeadzone, then we can ignore them. Recursion maybe...?

**Comment by spencrr** [comment]
Also, the contours could be filtered with size in the [GripPipeline](https://github.com/frc3197/2019-PiVision/blob/master/src/main/java/GripPipeline.java) file

**Comment by spencrr** [comment]
`double filterContoursMinArea = 400.0;`

**Comment by hexhounds** [comment]
Pseudocode for the second possible function
~~~~
double compareContourDifference(previousContourXs[index], contourXs[index]){
    double previousContourXs = new double[];
    double contourDeadzone = 0.1;
    if(Math.abs(previousContourXs[index] - contourXs[index]) <= contourDeadzone){
        //Insert code that will ignore these specific indexes
    }
    previousContourXs = contourXs[index];
    compareContourDifference(previousContourXs[index], contourXs[index]);
}
~~~~

**Comment by spencers0730** [comment]
increase possibly?

**Comment by hexhounds** [comment]
> Also, the contours could be filtered with size in the [GripPipeline](https://github.com/frc3197/2019-PiVision/blob/master/src/main/java/GripPipeline.java) file

That too. More GRIP messing yay~

**Comment by Jordan-Limonov** [comment]
There is also a case where you will see more than 2 objects without extra interference from cables etc.
Image coming soon.

**Comment by Jordan-Limonov** [comment]
![img_20190307_203542520](https://user-images.githubusercontent.com/32251990/54003920-62422280-4119-11e9-93bb-8cccfd695cba.jpg)

There is a case where we can see two sets of two vision targets. Best way of handling this would be to just use the two biggest ones. There will probably never be a case where the two biggest will not be part of the same set.

**Comment by Jordan-Limonov** [comment]
Using derivatives/change in size should also have a conditional where it is only called when the robot is driving (aka when the corresponding motors are having either encoder changes and/or have a current running through them)
Otherwise, whenever we pause those targets will end up becoming ignored and we'll have 0 targets and nothing will happen.

Filtering by size will also cause alignTurn to only be effective when the vision targets have a higher area than the consistent interference.

**Comment by hexhounds** [comment]
Another solution involves completely ignoring the bottom 50 or so pixels of the image.

Potentially couldn't work because of changes in the actual elevator, but should always work if elevator is down at home.

**Comment by spencrr** [comment]
Pi removed
